[advisories]
version = 2
unmaintained = "workspace"
unsound = "workspace"
yanked = "deny"
ignore = []

[licenses]
version = 2

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
