// EDEN GARM — Massive Corpus Generator (streaming procedural)
// Genera oraciones procedurales de alta diversidad sin límite.
// Puede producir billones de tokens bajo demanda.

#[derive(Clone, Debug)]
pub struct CorpusMassive {
    pub templates: Vec<String>,
    pub subjects: Vec<String>,
    pub verbs: Vec<String>,
    pub objects: Vec<String>,
    pub adjectives: Vec<String>,
    pub adverbs: Vec<String>,
    pub contexts: Vec<String>,
    pub generated_count: u64,
    pub seed: u64,
    // Hybrid real-world facts
    pub facts_countries: Vec<String>,
    pub facts_elements: Vec<String>,
    pub facts_planets: Vec<String>,
    pub facts_inventions: Vec<String>,
    pub facts_figures: Vec<String>,
    pub facts_animals: Vec<String>,
    pub facts_geo: Vec<String>,
    pub hybrid_templates: Vec<String>,
    // Executable program curriculum: templates that mix natural language with instructions
    pub program_templates: Vec<String>,
    pub program_keywords: Vec<String>,
    // Dynamic curriculum bias: probability of using program_templates (0.0..1.0)
    pub program_bias: f32,
}

fn to_strings(arr: &[&str]) -> Vec<String> {
    arr.iter().map(|s| s.to_string()).collect()
}

impl CorpusMassive {
    pub fn new() -> Self {
        CorpusMassive {
            templates: to_strings(&[
                "{subject} {verb} {object}",
                "{subject} {adverb} {verb} {adjective} {object}",
                "in {context}, {subject} {verb} {object}",
                "the {adjective} {subject} {adverb} {verb} the {object}",
                "{subject} and {subject} {verb} {object} together",
                "when {subject} {verb}, {object} becomes {adjective}",
                "{subject} learned that {object} can {verb} {adverb}",
                "because {subject} {verb}, the {context} changed",
                "the {object} of {subject} is {adjective}",
                "{adverb}, {subject} began to {verb} {object}",
                "unlike {object}, {subject} {verb} {adverb}",
                "{subject} {verb} {object} while {context}",
                "before {subject} {verb}, {object} was {adjective}",
                "after {subject} {verb}, {object} became {adjective}",
                "{subject} {verb} {object} because of {context}",
                "if {subject} {verb}, then {object} {verb}",
                "{subject} {verb} {adjective} {object} in {context}",
                "the {context} shows that {subject} {verb} {object}",
                "{subject} {adverb} {verb} {object} for the purpose of {context}",
                "{subject} {verb} {object} and then {subject} {verb} again",
            ]),
            subjects: to_strings(&[
                "agent","system","model","network","brain","mind","entity",
                "organism","robot","machine","algorithm","process","function",
                "structure","pattern","signal","concept","idea","theory","hypothesis",
                "framework","architecture","design","mechanism","component",
                "module","layer","node","vertex","edge","graph","tree",
                "forest","field","space","vector","matrix","tensor",
                "atom","molecule","cell","organ","body","creature","being",
                "individual","group","team","society","culture","civilization",
                "world","universe","cosmos","nature","reality","existence",
                "consciousness","awareness","perception","sensation","feeling",
                "emotion","desire","intention","goal","purpose","meaning",
                "value","belief","knowledge","understanding","wisdom","truth",
                "beauty","goodness","justice","freedom","power","force",
                "energy","matter","information","data","code","program",
                "language","symbol","sign","representation","image","form",
                "shape","color","sound","music","rhythm","harmony","balance",
                "order","chaos","change","growth","decay","death","life",
                "birth","origin","cause","effect","reason","result",
                "method","way","path","road","journey","travel","movement",
                "action","behavior","response","reaction","adaptation","evolution",
                "selection","survival","competition","cooperation","symbiosis",
                "conflict","peace","war","battle","struggle","effort","work",
                "labor","production","creation","invention","discovery",
                "exploration","experiment","test","trial","error","success",
                "failure","achievement","accomplishment","victory","defeat",
            ]),
            verbs: to_strings(&[
                "processes","transforms","computes","calculates","analyzes",
                "synthesizes","integrates","differentiates","learns","adapts",
                "evolves","grows","develops","changes","becomes","remains",
                "exists","persists","continues","stops","starts","begins",
                "ends","finishes","completes","achieves","fails","succeeds",
                "tries","attempts","strives","works","functions","operates",
                "performs","executes","runs","moves","acts","behaves",
                "responds","reacts","interacts","communicates","expresses",
                "represents","symbolizes","means","signifies","indicates",
                "shows","demonstrates","proves","verifies","confirms",
                "refutes","denies","rejects","accepts","approves","disapproves",
                "likes","dislikes","loves","hates","wants","needs","desires",
                "prefers","chooses","selects","decides","determines","resolves",
                "intends","plans","prepares","organizes","arranges","orders",
                "structures","constructs","builds","creates","makes","produces",
                "generates","forms","shapes","designs","models","simulates",
                "predicts","forecasts","expects","anticipates","hopes","fears",
                "doubts","believes","thinks","reasons","infers","concludes",
                "understands","knows","remembers","recalls","forgets","imagines",
                "perceives","senses","feels","experiences","enjoys","suffers",
                "observes","notices","recognizes","identifies","classifies",
                "categorizes","groups","separates","combines","joins","connects",
                "links","relates","associates","compares","contrasts",
                "measures","quantifies","counts","weighs","balances",
                "stabilizes","destabilizes","oscillates","fluctuates",
                "increases","decreases","rises","falls","expands","contracts",
                "accumulates","dissipates","concentrates","disperses",
                "attracts","repels","pushes","pulls","drives","guides",
                "leads","follows","precedes","succeeds","replaces","substitutes",
                "exchanges","trades","shares","distributes","collects",
                "gathers","scatters","spreads","transmits","receives",
                "sends","delivers","returns","retrieves","stores",
                "retains","releases","emits","absorbs","reflects",
                "resonates","vibrates","rotates","revolves","orbits","circulates",
                "flows","streams","pours","drips","leaks","floods","drains",
                "dries","wets","heats","cools","freezes","melts","boils",
                "condenses","evaporates","sublimates","crystallizes","dissolves",
                "mixes","stirs","shakes","blends","merges","unifies","divides",
                "splits","cuts","breaks","shatters","crushes","grinds",
                "polishes","smooths","roughens","sharpens","dulls",
                "brightens","darkens","lightens","deepens","shallows",
                "widens","narrows","lengthens","shortens","thickens","thins",
                "hardens","softens","stiffens","loosens","tightens","relaxes",
                "tenses","activates","deactivates","enables","disables",
                "empowers","weakens","strengthens","reinforces","undermines",
                "supports","opposes","resists","surrenders","yields","submits",
                "dominates","controls","governs","regulates","manages",
                "administers","coordinates","synchronizes","aligns","adjusts",
                "calibrates","tunes","optimizes","maximizes","minimizes",
                "satisfies","compromises","negotiates","bargains","deals",
                "transacts","invests","spends","saves","wastes","conserves",
                "preserves","protects","defends","guards","shields","shelters",
                "hides","conceals","reveals","exposes","discovers","uncovers",
                "dig","buries","plants","harvests","gathers","hunts","chases",
                "pursues","catches","captures","escapes","flees","avoids",
                "evades","prevents","stops","blocks","hinders","impedes",
                "delays","postpones","advances","promotes","encourages",
                "discourages","deters","dissuades","persuades","convinces",
                "influences","affects","effects","causes","triggers",
                "initiates","sparks","ignites","extinguishes","quenches",
                "satisfies","fulfills","completes","perfects","improves",
                "enhances","upgrades","updates","revises","edits","modifies",
                "alters","changes","varies","diversifies","unifies",
                "standardizes","normalizes","regularizes","randomizes",
                "systematizes","methodizes","formalizes","rationalizes",
                "justifies","explains","interprets","translates","converts",
                "transforms","transmutes","metamorphoses","evolves","mutates",
                "replicates","copies","duplicates","clones","mimics","imitates",
                "emulates","simulates","models","represents","depicts",
                "portrays","describes","characterizes","defines","specifies",
                "details","elaborates","expands","extends","stretches","reaches",
                "touches","contacts","connects","binds","ties","attaches",
                "detaches","separates","disconnects","isolates","insulates",
                "protects","preserves","maintains","sustains","nourishes",
                "feeds","eats","consumes","devours","digests","absorbs",
                "assimilates","excretes","secretes","produces","emits",
                "radiates","glows","shines","illuminates","darkens",
                "shadows","obscures","clouds","clears","clarifies",
                "purifies","cleans","washes","rinses","soaks","dries",
                "drains","empties","fills","packs","unpacks","loads",
                "unloads","carries","bears","holds","grasps","grips",
                "clutches","clings","releases","drops","falls","rises",
                "climbs","descends","ascends","mounts","dismounts","boards",
                "disembarks","enters","exits","leaves","arrives","departs",
                "travels","journeys","roams","wanders","explores","searches",
                "seeks","finds","locates","positions","places","puts","sets",
                "lays","stands","sits","lies","rests","sleeps","dreams",
                "imagines","fantasizes","daydreams","remembers","recalls",
                "reminisces","forgets","overlooks","ignores","neglects",
                "misses","loses","finds","recovers","retrieves","rescues",
                "saves","preserves","conserves","maintains","sustains",
                "endures","survives","outlives","outlasts","perseveres",
                "persists","resists","withstands","tolerates","endures",
                "suffers","bears","shoulders","carries","transports",
                "conveys","transmits","communicates","signals","indicates",
                "shows","displays","exhibits","demonstrates","illustrates",
                "exemplifies","embodies","incarnates","personifies","typifies",
                "characterizes","distinguishes","differentiates","discriminates",
                "separates","segregates","classifies","categorizes","groups",
                "clusters","assembles","gathers","collects","accumulates",
                "amasses","hoards","stores","stockpiles","reserves","saves",
                "spares","shares","distributes","dispenses","allocates",
                "assigns","allots","apportions","divides","splits","partitions",
                "segments","sections","fragments","shatters","smashes",
                "crushes","grinds","mills","pulverizes","atomizes","vaporizes",
                "evaporates","sublimates","condenses","liquefies","solidifies",
                "freezes","melts","thaws","warms","heats","cools","chills",
                "freezes","numbs","deadens","anesthetizes","sensitizes",
                "heightens","intensifies","amplifies","magnifies","enlarges",
                "expands","extends","prolongs","lengthens","stretches",
                "reaches","approaches","nears","closes","opens","shuts",
                "locks","unlocks","fastens","unfastens","ties","unties",
                "binds","unbinds","wraps","unwraps","covers","uncovers",
                "hides","reveals","masks","unmasks","disguises","exposes",
                "uncovers","discovers","invents","creates","originates",
                "initiates","launches","starts","begins","commences",
                "inaugurates","institutes","establishes","foundes",
                "constructs","erects","builds","assembles","fabricates",
                "manufactures","produces","generates","yields","bears",
                "delivers","gives","offers","provides","supplies","furnishes",
                "equips","arms","prepares","readies","conditions","trains",
                "drills","exercises","practices","rehearses","repeats",
                "iterates","cycles","loops","spirals","curves","bends",
                "twists","turns","rotates","revolves","spins","whirls",
                "swirls","edies","flows","streams","courses","runs","races",
                "speeds","hastens","hurries","rushes","dashes","sprints",
                "jogs","trots","gallops","walks","steps","paces","strides",
                "marches","parades","processes","proceeds","progresses",
                "advances","moves","shifts","transfers","transports",
                "conveys","transmits","broadcasts","publishes","announces",
                "proclaims","declares","states","asserts","affirms",
                "confirms","verifies","validates","authenticates","certifies",
                "guarantees","warrants","ensures","assures","secures",
                "safeguards","shields","guards","protects","defends",
                "resists","opposes","fights","battles","wars","contends",
                "competes","vies","rivals","challenges","defies","confronts",
                "faces","meets","encounters","experiences","undergoes",
                "suffers","endures","withstands","tolerates","accepts",
                "receives","welcomes","embraces","hugs","holds","grasps",
                "seizes","grabs","snatches","catches","captures","traps",
                "ensnares","entangles","tangles","complicates","simplifies",
                "eases","facilitates","smoothes","polishes","refines",
                "purifies","clarifies","cleans","washes","baths","soaks",
                "steams","boils","bakes","roasts","fries","grills","toasts",
                "burns","chars","scorches","sears","singes","ignites",
                "kindles","lights","illumines","brightens","enlightens",
                "informs","educates","teaches","instructs","trains",
                "coaches","tutors","mentors","guides","leads","directs",
                "steers","pilotes","navigates","sails","cruises","voyages",
                "journeys","travels","tours","visits","calls","phones",
                "rings","chimes","tones","sounds","noises","silences",
                "quiets","calms","soothes","comforts","consoles","solaces",
                "relieves","alleviates","mitigates","palliates","abates",
                "subsides","recedes","retreats","withdraws","retires",
                "resigns","quits","stops","ceases","halts","pauses",
                "breaks","interrupts","suspends","defers","delays",
                "postpones","reschedules","cancels","annuls","voids",
                "invalidates","negates","nullifies","revokes","repeals",
                "rescinds","abrogates","abolishes","eliminates",
                "eradicates","exterminates","destroys","demolishes",
                "ruins","wrecks","damages","harms","hurts","injures",
                "wounds","maims","mutilates","tortures","torments",
                "afflicts","plagues","troubles","disturbs","perturbs",
                "agitates","stirs","excites","stimulates","arouses",
                "awakens","rouses","revives","resuscitates","reanimates",
                "recharges","reenergizes","refreshes","renews","restores",
                "reinstates","reestablishes","reconstructs","rebuilds",
                "renovates","refurbishes","repairs","fixes","mends",
                "patches","heals","cures","remedies","corrects","rectifies",
                "amends","reforms","transforms","converts","transmutes",
                "metamorphoses","mutates","varies","changes","modifies",
                "adjusts","adapts","accommodates","fits","suits","matches",
                "corresponds","parallels","mirrors","reflects","echoes",
                "repeats","replicates","duplicates","copies","reproduces",
                "breeds","propagates","spawns","generates","begets",
                "creates","makes","forms","shapes","molds","casts",
                "forges","wroughtes","hammers","beats","pounds","strikes",
                "hits","slaps","pats","taps","touches","feels","senses",
                "perceives","notices","observes","watches","looks","sees",
                "views","regards","eyes","glimpses","glances","peers",
                "gazes","stares","contemplates","ponders","meditates",
                "reflects","muses","wonders","marvels","admires",
                "appreciates","esteems","values","treasures","cherishes",
                "loves","adores","worships","venerates","reveres","respects",
                "honors","praises","lauds","celebrates","commends",
                "recommends","endorses","approves","sanctions","ratifies",
                "confirms","validates","authorizes","empowers","enables",
                "permits","allows","lets","grants","gives","bestows",
                "confers","awards","presents","offers","proposes","suggests",
                "advises","counsels","warns","cautions","alerts","notifies",
                "informs","tells","reports","records","documents",
                "chronicles","registers","logs","tracks","monitors",
                "surveys","inspects","examines","investigates","studies",
                "researches","explores","probes","tests","trials",
                "experiments","demonstrates","proves","verifies",
                "confirms","establishes",
            ]),
            objects: to_strings(&[
                "data","information","knowledge","wisdom","truth",
                "result","output","input","signal","pattern",
                "structure","form","shape","image","model",
                "representation","concept","idea","thought",
                "memory","record","log","history","experience",
                "event","episode","moment","instant","period",
                "time","space","place","location","position",
                "point","line","plane","volume","area",
                "surface","boundary","edge","limit","threshold",
                "barrier","obstacle","block","wall","door",
                "window","opening","gap","space","room",
                "field","domain","realm","zone","region",
                "territory","land","ground","earth","soil",
                "rock","stone","metal","wood","water",
                "air","fire","light","darkness","shadow",
                "color","tone","sound","silence","noise",
                "music","voice","word","sentence","phrase",
                "text","document","file","record","archive",
                "library","collection","set","group","cluster",
                "network","web","mesh","grid","matrix",
                "array","list","queue","stack","heap",
                "tree","graph","diagram","chart","map",
                "plan","scheme","design","blueprint","layout",
                "framework","system","engine","machine","device",
                "tool","instrument","weapon","shield","armor",
                "vehicle","vessel","container","box","package",
                "bundle","load","burden","weight","mass",
                "matter","substance","material","element",
                "compound","mixture","solution","suspension",
                "emulsion","gel","foam","crystal","grain",
                "particle","atom","molecule","ion","electron",
                "proton","neutron","quark","boson","fermion",
                "photon","wave","vibration","oscillation",
                "resonance","harmony","dissonance","chaos",
                "order","organization","disorder","entropy",
                "energy","force","power","strength","intensity",
                "magnitude","amplitude","frequency","wavelength",
                "speed","velocity","acceleration","momentum",
                "impulse","inertia","mass","density","pressure",
                "temperature","heat","cold","warmth","coolness",
                "charge","current","voltage","resistance",
                "conductance","capacitance","inductance",
                "magnetism","electricity","gravity","levity",
                "buoyancy","tension","compression","shear",
                "stress","strain","deformation","displacement",
                "movement","motion","action","reaction",
                "interaction","relation","connection","link",
                "bond","tie","attachment","affinity","attraction",
                "repulsion","aversion","sympathy","empathy",
                "compassion","kindness","cruelty","brutality",
                "violence","peace","calm","tranquility",
                "serenity","harmony","balance","equilibrium",
                "stability","instability","change","flux",
                "flow","current","stream","river","ocean",
                "sea","lake","pond","pool","puddle",
                "drop","droplet","mist","fog","cloud",
                "rain","snow","ice","hail","sleet",
                "dew","frost","crystal","gem","jewel",
                "treasure","wealth","riches","gold","silver",
                "bronze","copper","iron","steel","lead",
                "tin","zinc","nickel","chrome","platinum",
                "palladium","titanium","aluminum","magnesium",
                "calcium","potassium","sodium","lithium",
                "hydrogen","oxygen","nitrogen","carbon",
                "sulfur","phosphorus","chlorine","fluorine",
                "iodine","bromine","radium","uranium",
                "plutonium","neptunium","americium","curium",
                "berkelium","californium","einsteinium","fermium",
                "mendelevium","nobelium","lawrencium","rutherfordium",
                "dubnium","seaborgium","bohrium","hassium",
                "meitnerium","darmstadtium","roentgenium",
                "copernicium","nihonium","flerovium","moscovium",
                "livermorium","tennessine","oganesson",
            ]),
            adjectives: to_strings(&[
                "big","small","large","tiny","huge","minute",
                "great","little","massive","immense","vast",
                "wide","narrow","broad","slender","thick",
                "thin","deep","shallow","tall","short",
                "high","low","long","brief","endless",
                "finite","infinite","eternal","temporary",
                "permanent","constant","variable","changing",
                "stable","unstable","steady","wavering",
                "firm","loose","tight","rigid","flexible",
                "elastic","plastic","brittle","tough",
                "strong","weak","powerful","feeble",
                "mighty","frail","hard","soft","smooth",
                "rough","coarse","fine","sharp","dull",
                "keen","blunt","clear","opaque","transparent",
                "translucent","luminous","dark","bright",
                "dim","brilliant","radiant","gloomy",
                "cheerful","sad","happy","melancholy",
                "joyful","sorrowful","elated","depressed",
                "excited","calm","agitated","peaceful",
                "turbulent","quiet","noisy","silent",
                "loud","faint","distinct","vague",
                "precise","accurate","exact","approximate",
                "rough","true","false","real","unreal",
                "actual","potential","possible","impossible",
                "probable","improbable","certain","uncertain",
                "sure","unsure","doubtful","confident",
                "optimistic","pessimistic","hopeful","hopeless",
                "positive","negative","neutral","partial",
                "total","complete","incomplete","whole",
                "full","empty","filled","vacant",
                "occupied","available","unavailable","accessible",
                "inaccessible","open","closed","free",
                "bound","liberated","enslaved","independent",
                "dependent","autonomous","controlled","master",
                "slave","superior","inferior","equal",
                "different","similar","dissimilar","alike",
                "unlike","related","unrelated","connected",
                "disconnected","joined","separated","united",
                "divided","coherent","incoherent","consistent",
                "inconsistent","logical","illogical","rational",
                "irrational","sensible","absurd","reasonable",
                "unreasonable","just","unjust","fair","unfair",
                "impartial","biased","objective","subjective",
                "universal","particular","general","specific",
                "abstract","concrete","theoretical","practical",
                "applied","pure","mixed","simple","complex",
                "complicated","intricate","plain","fancy","ornate",
                "bare","naked","clothed","covered","exposed",
                "hidden","visible","invisible","apparent",
                "obvious","subtle","manifest","latent",
                "active","passive","dynamic","static","kinetic",
                "potential","resting","moving","still","agitated",
                "composed","nervous","relaxed","tense","loose",
                "rigid","flexible","adaptable","inflexible",
                "versatile","limited","boundless","restricted",
                "unrestricted","controlled","free","wild","tame",
                "domestic","foreign","native","alien","familiar",
                "strange","known","unknown","famous","obscure",
                "renowned","infamous","celebrated","notorious",
                "distinguished","common","rare","unique","special",
                "ordinary","extraordinary","typical","atypical",
                "normal","abnormal","standard","nonstandard",
                "regular","irregular","uniform","varied",
                "homogeneous","heterogeneous","consistent","erratic",
                "systematic","random","ordered","disordered",
                "organized","chaotic","structured","amorphous",
                "crystalline","granular","smooth","polished",
                "rough","raw","refined","crude","processed",
                "natural","artificial","synthetic","organic",
                "inorganic","biological","mechanical","electrical",
                "electronic","digital","analog","virtual",
                "physical","mental","spiritual","material",
                "immaterial","tangible","intangible","solid",
                "liquid","gaseous","plasma","aqueous",
                "terrestrial","aquatic","aerial","subterranean",
                "celestial","mundane","divine","profane",
                "sacred","secular","holy","unholy","blessed",
                "cursed","fortunate","unfortunate","lucky",
                "unlucky","favored","disfavored","loved","hated",
                "desired","undesired","wanted","unwanted",
                "needed","unneeded","essential","inessential",
                "necessary","unnecessary","vital","fatal",
                "deadly","harmless","dangerous","safe","risky",
                "secure","vulnerable","protected","exposed",
                "immune","susceptible","resistant","fragile",
                "robust","delicate","sturdy","durable",
                "perishable","eternal","mortal","immortal",
                "living","dead","alive","animate","inanimate",
                "conscious","unconscious","aware","unaware",
                "sentient","insentient","intelligent",
                "unintelligent","smart","dumb","clever",
                "stupid","wise","foolish","brilliant","dim",
                "bright","dull","sharp","slow","fast","quick",
                "rapid","gradual","sudden","expected","unexpected",
                "predictable","unpredictable","foreseen","unforeseen",
                "intentional","accidental","deliberate","involuntary",
                "voluntary","forced","willing","eager","reluctant",
                "enthusiastic","apathetic","passionate","indifferent",
                "interested","disinterested","curious","incurious",
                "inquisitive","uninquisitive","questioning","accepting",
                "skeptical","believing","doubting","trusting",
                "mistrustful","faithful","faithless","loyal",
                "disloyal","devoted","undevoted","committed",
                "uncommitted","dedicated","undedicated",
                "responsible","irresponsible","accountable",
                "unaccountable","liable","immune","guilty",
                "innocent","pure","corrupt","honest","dishonest",
                "sincere","insincere","genuine","fake","authentic",
                "counterfeit","original","copy","novel","derivative",
                "creative","imitative","innovative","traditional",
                "conservative","progressive","reactionary","radical",
                "moderate","extreme","mild","intense","fierce",
                "gentle","violent","peaceful","aggressive",
                "defensive","offensive","protective","predatory",
                "hunter","gatherer","producer","consumer","creator",
                "destroyer","builder","breaker","maker","unmaker",
                "beginner","finisher","starter","ender","opener",
                "closer","winner","loser","victor","vanquished",
                "champion","underdog","leader","follower","pioneer",
                "settler","explorer","conqueror","liberator",
                "oppressor","victim","survivor","casualty",
                "beneficiary","contributor","burden","asset",
                "liability","advantage","disadvantage","strength",
                "weakness","virtue","vice","merit","flaw",
                "perfection","imperfection","defect","quality",
                "property","attribute","characteristic","trait",
                "feature","aspect","facet","phase","stage","level",
                "degree","grade","rank","class","category","type",
                "kind","sort","species","genus","family","order",
                "class","phylum","kingdom","domain","realm",
                "sphere","world","universe","multiverse","dimension",
            ]),
            adverbs: to_strings(&[
                "quickly","slowly","rapidly","gradually","suddenly",
                "immediately","eventually","finally","initially",
                "originally","previously","subsequently",
                "consequently","therefore","thus","hence",
                "accordingly","similarly","likewise","conversely",
                "otherwise","instead","rather","quite","very",
                "extremely","moderately","slightly","barely",
                "hardly","scarcely","nearly","almost","approximately",
                "exactly","precisely","accurately","correctly",
                "incorrectly","wrongly","properly","improperly",
                "appropriately","inappropriately","suitably",
                "unsuitably","adequately","inadequately",
                "sufficiently","insufficiently","completely",
                "incompletely","totally","partially","fully",
                "half","wholly","entirely","solely","only",
                "merely","just","simply","purely","clearly",
                "obviously","evidently","apparently","seemingly",
                "presumably","probably","possibly","perhaps",
                "maybe","certainly","definitely","absolutely",
                "relatively","comparatively","extremely",
                "intensely","strongly","weakly","firmly",
                "loosely","tightly","strictly","leniently",
                "severely","mildly","harshly","gently","softly",
                "loudly","quietly","silently","noisily",
                "calmly","peacefully","violently","aggressively",
                "defensively","offensively","actively","passively",
                "dynamically","statically","automatically",
                "manually","consciously","unconsciously",
                "deliberately","accidentally","intentionally",
                "unintentionally","voluntarily","involuntarily",
                "freely","forcibly","willingly","unwillingly",
                "eagerly","reluctantly","enthusiastically",
                "apathetically","passionately","indifferently",
                "interestingly","boringly","curiously",
                "inquisitively","skeptically","believingly",
                "doubtfully","trustingly","mistrustfully",
                "faithfully","faithlessly","loyally","disloyally",
                "devotedly","responsibly","irresponsibly",
                "honestly","dishonestly","sincerely",
                "insincerely","genuinely","authentically",
                "originally","creatively","innovatively",
                "traditionally","conservatively","progressively",
                "radically","moderately","extremely","mildly",
                "intensely","fiercely","gently","violently",
                "peacefully","aggressively","successfully",
                "unsuccessfully","effectively","ineffectively",
                "efficiently","inefficiently","optimally",
                "suboptimally","perfectly","imperfectly",
                "directly","indirectly","straight","crookedly",
                "forward","backward","upward","downward",
                "inward","outward","sideways","around","about",
                "here","there","everywhere","somewhere",
                "nowhere","elsewhere","above","below","over",
                "under","beneath","beyond","within","without",
                "inside","outside","together","apart","alone",
                "jointly","separately","collectively",
                "individually","mutually","reciprocally",
                "alternatively","simultaneously",
                "consecutively","sequentially","parallelly",
                "orthogonally","independently","dependently",
            ]),
            contexts: to_strings(&[
                "the morning","the evening","the night","the dawn",
                "the dusk","the twilight","the noon","the midnight",
                "spring","summer","autumn","winter","the rain",
                "the sunshine","the darkness","the light","the fog",
                "the storm","the calm","the silence","the noise",
                "the city","the forest","the ocean","the mountain",
                "the desert","the valley","the river","the lake",
                "the garden","the house","the room","the hall",
                "the field","the road","the path","the journey",
                "the beginning","the end","the middle","the edge",
                "the center","the periphery","the core","the surface",
                "the depth","the height","the distance","the proximity",
                "the past","the present","the future","the moment",
                "the instant","the eternity","the blink","the age",
                "the era","the epoch","the period","the season",
                "the cycle","the loop","the spiral","the wave",
                "the vibration","the resonance","the harmony",
                "the chaos","the order","the pattern","the random",
                "the system","the network","the web","the mesh",
                "the grid","the matrix","the array","the structure",
                "the framework","the architecture","the design",
                "the plan","the scheme","the model","the theory",
                "the hypothesis","the assumption","the premise",
                "the conclusion","the result","the outcome",
                "the effect","the cause","the reason","the purpose",
                "the goal","the aim","the objective","the target",
                "the method","the way","the manner","the mode",
                "the process","the procedure","the protocol",
                "the standard","the norm","the rule","the law",
                "the principle","the value","the belief","the idea",
                "the thought","the concept","the notion","the view",
                "the perspective","the angle","the aspect","the facet",
                "the dimension","the level","the layer","the stratum",
                "the tier","the stage","the phase","the state",
                "the condition","the situation","the circumstance",
                "the context","the environment","the setting",
                "the background","the foreground","the scene",
                "the picture","the image","the vision","the dream",
                "the reality","the illusion","the fantasy","the memory",
                "the expectation","the hope","the fear","the desire",
                "the need","the want","the demand","the supply",
                "the market","the economy","the society","the culture",
                "the civilization","the world","the universe",
                "the cosmos","the existence","the being","the nothing",
                "the everything","the all","the none","the some",
                "the many","the few","the one","the multiple",
                "the singular","the plural","the unique","the common",
                "the special","the general","the particular",
                "the universal","the local","the global","the cosmic",
                "the micro","the macro","the mega","the nano",
                "the quantum","the classical","the modern","the ancient",
                "the new","the old","the young","the mature",
                "the immature","the developed","the undeveloped",
                "the advanced","the primitive","the complex",
                "the simple","the easy","the difficult","the hard",
                "the soft","the rigid","the flexible","the strong",
                "the weak","the powerful","the powerless","the rich",
                "the poor","the wealthy","the needy","the abundant",
                "the scarce","the full","the empty","the complete",
                "the incomplete","the perfect","the imperfect",
                "the beautiful","the ugly","the attractive",
                "the repulsive","the pleasant","the unpleasant",
                "the comfortable","the uncomfortable","the safe",
                "the dangerous","the secure","the insecure",
                "the stable","the unstable","the certain",
                "the uncertain","the known","the unknown",
                "the familiar","the strange","the normal",
                "the abnormal","the natural","the artificial",
                "the real","the unreal","the true","the false",
                "the valid","the invalid","the sound","the unsound",
                "the healthy","the sick","the alive","the dead",
                "the conscious","the unconscious","the aware",
                "the unaware","the mindful","the mindless",
            ]),
            // Real-world facts for hybrid generation
            facts_countries: to_strings(&[
                "argentina","brazil","canada","china","egypt","france","germany",
                "india","italy","japan","mexico","nigeria","pakistan","russia",
                "south africa","spain","turkey","united kingdom","united states",
                "australia","bangladesh","ethiopia","indonesia","iran","iraq",
                "israel","kenya","malaysia","morocco","netherlands","norway",
                "peru","philippines","poland","saudi arabia","singapore",
                "south korea","sweden","switzerland","thailand","vietnam",
            ]),
            facts_elements: to_strings(&[
                "hydrogen","helium","lithium","beryllium","boron","carbon",
                "nitrogen","oxygen","fluorine","neon","sodium","magnesium",
                "aluminum","silicon","phosphorus","sulfur","chlorine","argon",
                "potassium","calcium","iron","copper","zinc","silver","gold",
                "mercury","lead","uranium","plutonium","radium","titanium",
                "chromium","manganese","cobalt","nickel","platinum","tin",
            ]),
            facts_planets: to_strings(&[
                "mercury","venus","earth","mars","jupiter","saturn","uranus",
                "neptune","pluto","the moon","the sun","io","europa","titan",
                "enceladus","ganymede","callisto","triton","charon",
            ]),
            facts_inventions: to_strings(&[
                "the wheel","the printing press","electricity","the telephone",
                "the light bulb","the airplane","the internet","the computer",
                "the steam engine","vaccination","penicillin","radio",
                "television","the automobile","the rocket","antibiotics",
                "the transistor","the laser","fiber optics","the microscope",
                "the telescope","photography","refrigeration","nuclear power",
            ]),
            facts_figures: to_strings(&[
                "isaac newton","albert einstein","marie curie","charles darwin",
                "galileo galilei","nikola tesla","leonardo da vinci",
                "marie antoinette","napoleon bonaparte","genghis khan",
                "cleopatra","aristotle","plato","socrates","confucius",
                "maya angelou","nelson mandela","mahatma gandhi",
                "martin luther king jr","rosa parks","ada lovelace",
                "alan turing","grace hopper","hypatia","ibn sina",
            ]),
            facts_animals: to_strings(&[
                "the lion","the tiger","the elephant","the giraffe","the penguin",
                "the dolphin","the eagle","the wolf","the bear","the kangaroo",
                "the panda","the cheetah","the gorilla","the octopus",
                "the hawk","the salmon","the bumblebee","the ant",
                "the jellyfish","the crocodile","the rhinoceros","the flamingo",
                "the chameleon","the owl","the raven","the horse",
            ]),
            facts_geo: to_strings(&[
                "the amazon river","the nile","the mississippi","the yangtze",
                "the ganges","the danube","the thames","the euphrates",
                "mount everest","kilimanjaro","mont blanc","the alps",
                "the himalayas","the andes","the rockies","the sahara",
                "the gobi desert","the pacific ocean","the atlantic",
                "the indian ocean","the mediterranean sea","the caribbean",
                "the black forest","the grand canyon","the great barrier reef",
                "the amazon rainforest","siberia","the serengeti",
            ]),
            program_templates: to_strings(&[
                "{subject} SETGOAL {prog_keyword} {prog_num}",
                "the {adjective} {subject} INVOKE {prog_keyword} and SETGOAL {prog_keyword} {prog_num}",
                "when {context} the {subject} TOOLCALL {prog_keyword} {prog_arg}",
                "{subject} TRAIN_TF {prog_num} and then SETGOAL {prog_keyword} {prog_num}",
                "in {context} {subject} WAIT {prog_num} then INVOKE {prog_keyword}",
                "the {adjective} {subject} READ_BUS {prog_keyword} and WRITE_BUS {prog_keyword} {prog_num}",
                "if {subject} SETGOAL {prog_keyword} {prog_num} then {subject} TOOLCALL {prog_keyword} {prog_arg}",
                "{subject} LOG {prog_arg} and WAIT {prog_num}",
                "the {object} of {subject} is {adjective} so SETGOAL {prog_keyword} {prog_num}",
                "{subject} INVOKE {prog_keyword} while {subject} TRAIN_TF {prog_num}",
                "because {context} the {subject} WRITE_BUS {prog_keyword} {prog_num} and LOG {prog_arg}",
                "{subject} discovered that {object} can {verb} so TOOLCALL {prog_keyword} {prog_arg}",
                "the {adjective} {subject} began to INVOKE {prog_keyword} and SETGOAL {prog_keyword} {prog_num}",
                "after {subject} TRAIN_TF {prog_num} the {context} changed and WAIT {prog_num}",
                "unlike {object} {subject} INVOKE {prog_keyword} and READ_BUS {prog_keyword}",
                "{subject} {adverb} SETGOAL {prog_keyword} {prog_num} for the purpose of {context}",
                "{subject} WAIT {prog_num} and then {subject} TOOLCALL {prog_keyword} {prog_arg}",
                "the {context} shows that {subject} should INVOKE {prog_keyword} and TRAIN_TF {prog_num}",
                "{subject} {adverb} INVOKE {prog_keyword} and WRITE_BUS {prog_keyword} {prog_num}",
                "before {subject} SETGOAL {prog_keyword} {prog_num} the {object} was {adjective}",
            ]),
            program_keywords: to_strings(&[
                "planner","morphogenesis","selfmodel","metacognition","causality",
                "motivation","mood","worldmodel","autonomy","tools","bigtransformer",
                "vision","calculator","search","file","network","process",
                "explore","learn","build","optimize","defend","create","analyze",
                "motivation","prediction","curiosity","efficiency","safety","goal",
                "attention","memory","perception","action","plan","strategy",
                "bus","workspace","concepts","tokens","sentences","steps",
                "tick","energy","goal","action","calm","happy","sad","angry",
                "setgoal","invoke","toolcall","train_tf","wait","read_bus",
                "write_bus","log","halt",
            ]),
            hybrid_templates: to_strings(&[
                "{subject} discovered that {fact_country} borders {fact_country}",
                "the invention of {fact_invention} changed {fact_country} forever",
                "{fact_figure} proved that {fact_element} is essential for life",
                "scientists in {fact_country} found {fact_animal} near {fact_geo}",
                "{fact_planet} is larger than {fact_planet} but smaller than {fact_geo}",
                "the {fact_invention} was created before {fact_figure} was born",
                "{fact_animal} migrates across {fact_geo} every year",
                "explorers from {fact_country} mapped {fact_geo} in the 15th century",
                "{fact_figure} used {fact_element} to build {fact_invention}",
                "the atmosphere of {fact_planet} contains traces of {fact_element}",
                "{fact_geo} is longer than {fact_geo} but shorter than {fact_geo}",
                "researchers observed {fact_animal} in {fact_country} and published findings",
                "{fact_figure} believed that {fact_planet} orbits {fact_planet}",
                "the discovery of {fact_element} led to {fact_invention}",
                "pollution in {fact_geo} threatens {fact_animal} populations",
                "{fact_country} exports more {fact_element} than {fact_country}",
                "the temperature on {fact_planet} exceeds that of {fact_geo}",
                "historians claim {fact_figure} visited {fact_country} twice",
                "the ecosystem of {fact_geo} supports {fact_animal} and {fact_animal}",
                "engineers tested {fact_invention} near {fact_geo} with success",
                "astronomers detected {fact_element} on {fact_planet} using {fact_invention}",
                "the border between {fact_country} and {fact_country} crosses {fact_geo}",
                "{fact_figure} wrote about {fact_animal} and {fact_element} in her notes",
                "the depth of {fact_geo} was measured by {fact_country} scientists",
                "navigation from {fact_geo} to {fact_geo} requires crossing {fact_geo}",
                "the population of {fact_country} studies {fact_figure} in schools",
                "{fact_planet} has less gravity than {fact_planet} but more than {fact_planet}",
            ]),
            generated_count: 0,
            seed: 123456789,
            program_bias: 0.3,
        }
    }

    fn rand(&mut self) -> usize {
        self.seed = self.seed.wrapping_mul(1103515245).wrapping_add(12345);
        (self.seed >> 16) as usize
    }

    /// Return all unique individual words from the entire hybrid vocabulary.
    pub fn all_words(&self) -> Vec<String> {
        let mut set = std::collections::HashSet::new();
        for list in &[
            &self.subjects,
            &self.verbs,
            &self.objects,
            &self.adjectives,
            &self.adverbs,
            &self.contexts,
            &self.facts_countries,
            &self.facts_elements,
            &self.facts_planets,
            &self.facts_inventions,
            &self.facts_figures,
            &self.facts_animals,
            &self.facts_geo,
            &self.program_keywords,
        ] {
            for phrase in *list {
                for word in phrase
                    .to_lowercase()
                    .split(|c: char| !c.is_alphanumeric())
                    .filter(|w| !w.is_empty())
                {
                    set.insert(word.to_string());
                }
            }
        }
        // Also extract words from program templates (includes instruction keywords like SETGOAL, INVOKE, etc.)
        for tmpl in &self.program_templates {
            for word in tmpl
                .to_lowercase()
                .split(|c: char| !c.is_alphanumeric())
                .filter(|w| !w.is_empty())
            {
                set.insert(word.to_string());
            }
        }
        set.into_iter().collect()
    }

    /// Generate a single procedural, hybrid, or program-curriculum sentence.
    pub fn next_sentence(&mut self) -> Option<String> {
        if self.templates.is_empty() {
            return None;
        }
        let roll = self.rand() % 10;
        let threshold = (self.program_bias * 10.0).clamp(0.0, 10.0) as usize;
        let use_program = !self.program_templates.is_empty() && roll < threshold; // program_bias % program curriculum
        let use_hybrid =
            !use_program && !self.hybrid_templates.is_empty() && (self.rand() % 2 == 0);
        let tmpl_idx = if use_program {
            self.rand() % self.program_templates.len()
        } else if use_hybrid {
            self.rand() % self.hybrid_templates.len()
        } else {
            self.rand() % self.templates.len()
        };
        // Precompute all random indices to avoid multiple mutable borrows
        let s_idx = self.rand() % self.subjects.len().max(1);
        let v_idx = self.rand() % self.verbs.len().max(1);
        let o_idx = self.rand() % self.objects.len().max(1);
        let a_idx = self.rand() % self.adjectives.len().max(1);
        let av_idx = self.rand() % self.adverbs.len().max(1);
        let c_idx = self.rand() % self.contexts.len().max(1);
        let fc_idx = self.rand() % self.facts_countries.len().max(1);
        let fe_idx = self.rand() % self.facts_elements.len().max(1);
        let fp_idx = self.rand() % self.facts_planets.len().max(1);
        let fi_idx = self.rand() % self.facts_inventions.len().max(1);
        let ff_idx = self.rand() % self.facts_figures.len().max(1);
        let fa_idx = self.rand() % self.facts_animals.len().max(1);
        let fg_idx = self.rand() % self.facts_geo.len().max(1);
        let pk_idx = self.rand() % self.program_keywords.len().max(1);
        let prog_num = (self.rand() % 9 + 1).to_string(); // 1..9
        let prog_arg = match self.rand() % 4 {
            0 => "explore".to_string(),
            1 => "2+2".to_string(),
            2 => "mission".to_string(),
            _ => "build".to_string(),
        };

        let tmpl = if use_hybrid {
            self.hybrid_templates[tmpl_idx].clone()
        } else {
            self.templates[tmpl_idx].clone()
        };
        let s = self.subjects.get(s_idx).cloned().unwrap_or_default();
        let v = self.verbs.get(v_idx).cloned().unwrap_or_default();
        let o = self.objects.get(o_idx).cloned().unwrap_or_default();
        let a = self.adjectives.get(a_idx).cloned().unwrap_or_default();
        let av = self.adverbs.get(av_idx).cloned().unwrap_or_default();
        let c = self.contexts.get(c_idx).cloned().unwrap_or_default();
        let mut sentence = tmpl
            .replace("{subject}", &s)
            .replace("{verb}", &v)
            .replace("{object}", &o)
            .replace("{adjective}", &a)
            .replace("{adverb}", &av)
            .replace("{context}", &c);
        if use_hybrid {
            sentence = sentence.replace(
                "{fact_country}",
                &self
                    .facts_countries
                    .get(fc_idx)
                    .cloned()
                    .unwrap_or_default(),
            );
            sentence = sentence.replace(
                "{fact_element}",
                &self.facts_elements.get(fe_idx).cloned().unwrap_or_default(),
            );
            sentence = sentence.replace(
                "{fact_planet}",
                &self.facts_planets.get(fp_idx).cloned().unwrap_or_default(),
            );
            sentence = sentence.replace(
                "{fact_invention}",
                &self
                    .facts_inventions
                    .get(fi_idx)
                    .cloned()
                    .unwrap_or_default(),
            );
            sentence = sentence.replace(
                "{fact_figure}",
                &self.facts_figures.get(ff_idx).cloned().unwrap_or_default(),
            );
            sentence = sentence.replace(
                "{fact_animal}",
                &self.facts_animals.get(fa_idx).cloned().unwrap_or_default(),
            );
            sentence = sentence.replace(
                "{fact_geo}",
                &self.facts_geo.get(fg_idx).cloned().unwrap_or_default(),
            );
        }
        if use_program {
            sentence = sentence.replace(
                "{prog_keyword}",
                &self
                    .program_keywords
                    .get(pk_idx)
                    .cloned()
                    .unwrap_or_default(),
            );
            sentence = sentence.replace("{prog_num}", &prog_num);
            sentence = sentence.replace("{prog_arg}", &prog_arg);
        }
        self.generated_count += 1;
        Some(sentence)
    }

    /// Generate N sentences.
    pub fn generate_n(&mut self, n: usize) -> Vec<String> {
        (0..n).filter_map(|_| self.next_sentence()).collect()
    }

    pub fn status(&self) -> String {
        let vocab_pure = self.subjects.len()
            + self.verbs.len()
            + self.objects.len()
            + self.adjectives.len()
            + self.adverbs.len()
            + self.contexts.len();
        let vocab_facts = self.facts_countries.len()
            + self.facts_elements.len()
            + self.facts_planets.len()
            + self.facts_inventions.len()
            + self.facts_figures.len()
            + self.facts_animals.len()
            + self.facts_geo.len();
        format!("CorpusMassive | generated={} | pure_templates={} | hybrid_templates={} | program_templates={} | pure_vocab={} | fact_vocab={} | prog_vocab={}",
            self.generated_count, self.templates.len(), self.hybrid_templates.len(), self.program_templates.len(), vocab_pure, vocab_facts, self.program_keywords.len())
    }
}
