//! Neuroplast - Eden's Neuroplasticity System
//!
//! Eden rewrites its own routing rules based on accumulated experience.
//! It learns which agents perform better at which tasks and creates
//! new routing rules in real-time.
#![allow(dead_code)]
#![allow(non_snake_case)]

use crate::membrain::{generate_id, MemBrain, NOW_MS};
const RULES_FILE: &str = "/home/ubuntu/orchestrator/rules.json";
const NEUROPLAST_INTERVAL_HOURS: u64 = 6;

/// Routing rule generated by neuroplasticity
#[derive(Debug, Clone)]
pub struct RoutingRule {
    pub id: String,
    pub task_type: String,
    pub preferred_agent: String,
    pub confidence: f64,
    pub generated_at: u64,
    pub source: String,
}

impl RoutingRule {
    pub fn new(task_type: String, preferred_agent: String, confidence: f64) -> Self {
        let id_data = format!("{}:{}:{}", task_type, preferred_agent, confidence);
        RoutingRule {
            id: generate_id(id_data.as_bytes()).to_string(),
            task_type,
            preferred_agent,
            confidence,
            generated_at: NOW_MS(),
            source: "neuroplasticity".to_string(),
        }
    }
}

/// Rules manifest
#[derive(Debug, Clone)]
pub struct RulesManifest {
    pub version: String,
    pub generated_at: u64,
    pub rules_count: usize,
    pub rules: Vec<RoutingRule>,
}

/// Experience data accumulated
#[derive(Debug, Clone)]
struct ExperienceData {
    router_weights: Vec<(String, String, f64)>,
    selection_events: Vec<(String, String, u64)>,
    evaluations: Vec<(String, String, f64, f64)>,
}

/// Read experience from MemBrain
fn read_experience(_db: &mut MemBrain) -> ExperienceData {
    let now = NOW_MS();
    let _twenty_four_hours_ago = now - 86_400_000;

    // Read router weights - query returns empty vec since MemBrain doesn't have tables
    let router_weights: Vec<(String, String, f64)> = Vec::new();

    // Read selection events from last 24h - query returns empty vec
    let selection_events: Vec<(String, String, u64)> = Vec::new();

    // Read evaluations - query returns empty vec
    let evaluations: Vec<(String, String, f64, f64)> = Vec::new();

    ExperienceData {
        router_weights,
        selection_events,
        evaluations,
    }
}

/// Generate new rules based on experience
fn generate_new_rules(experience: &ExperienceData) -> Vec<RoutingRule> {
    let improvement_threshold = 0.30;
    let mut new_rules = Vec::new();

    // Group evaluations by task type
    let mut agent_performance: std::collections::HashMap<
        String,
        std::collections::HashMap<String, Vec<f64>>,
    > = std::collections::HashMap::new();

    for (task_type, agent, success_rate, _) in &experience.evaluations {
        agent_performance
            .entry(task_type.clone())
            .or_default()
            .entry(agent.clone())
            .or_default()
            .push(*success_rate);
    }

    // For each task type, compare agent performances
    for (task_type, agents) in &agent_performance {
        if agents.len() < 2 {
            continue;
        }

        // Calculate average success rate per agent
        let mut agent_avgs: Vec<(&String, f64)> = agents
            .iter()
            .map(|(agent, rates)| {
                let avg = if rates.is_empty() {
                    0.0
                } else {
                    rates.iter().sum::<f64>() / rates.len() as f64
                };
                (agent, avg)
            })
            .collect();

        agent_avgs.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

        // Check if best agent is significantly better
        if let Some((best_agent, best_rate)) = agent_avgs.first() {
            if let Some((_second_agent, second_rate)) = agent_avgs.get(1) {
                if *best_rate > 0.0 {
                    let improvement = (best_rate - second_rate) / best_rate;

                    if improvement > improvement_threshold {
                        let confidence = improvement.min(0.99);

                        new_rules.push(RoutingRule::new(
                            task_type.clone(),
                            (*best_agent).clone(),
                            confidence,
                        ));

                        println!(
                            "[NEUROPLAST] Nueva regla: {} → {} (confianza: {:.1}%)",
                            task_type,
                            best_agent,
                            confidence * 100.0
                        );
                    }
                }
            }
        }
    }

    new_rules
}

/// Apply rules to rules.json
fn apply_rules_hot(rules: &[RoutingRule], rules_file: &str) {
    use std::fs;
    use std::path::Path;

    // Create orchestrator directory if needed
    if let Some(parent) = Path::new(rules_file).parent() {
        fs::create_dir_all(parent).ok();
    }

    // Save to file (simple JSON-like format)
    let mut content = String::new();
    content.push_str("{\n");
    content.push_str("  \"version\": \"1.0\",\n");
    content.push_str(&format!("  \"generated_at\": {},\n", NOW_MS()));
    content.push_str(&format!("  \"rules_count\": {},\n", rules.len()));
    content.push_str("  \"rules\": [\n");

    for (i, rule) in rules.iter().enumerate() {
        content.push_str("    {\n");
        content.push_str(&format!("      \"id\": \"{}\",\n", rule.id));
        content.push_str(&format!("      \"task_type\": \"{}\",\n", rule.task_type));
        content.push_str(&format!(
            "      \"preferred_agent\": \"{}\",\n",
            rule.preferred_agent
        ));
        content.push_str(&format!("      \"confidence\": {:.4},\n", rule.confidence));
        content.push_str(&format!("      \"generated_at\": {},\n", rule.generated_at));
        content.push_str(&format!("      \"source\": \"{}\"\n", rule.source));
        content.push_str("    }");
        if i < rules.len() - 1 {
            content.push(',');
        }
        content.push('\n');
    }

    content.push_str("  ]\n");
    content.push('}');

    if let Err(e) = fs::write(rules_file, content) {
        eprintln!("[NEUROPLAST] Error escribiendo rules.json: {}", e);
    } else {
        println!(
            "[NEUROPLAST] rules.json actualizado con {} reglas",
            rules.len()
        );
    }
}

/// Start neuroplasticity system
pub fn start_neuroplast() {
    println!(
        "[NEUROPLAST] Sistema de neuroplasticidad iniciado - intervalo {}h",
        NEUROPLAST_INTERVAL_HOURS
    );

    // Run initial cycle
    run_neuroplasticity_cycle();
}

/// Run one neuroplasticity cycle
pub fn run_neuroplasticity_cycle() {
    println!("[NEUROPLAST] Iniciando ciclo de neuroplasticidad...");

    // Open MemBrain
    let mut db = match MemBrain::new("/home/ubuntu/eden_kg") {
        Ok(db) => db,
        Err(e) => {
            eprintln!("[NEUROPLAST] Error abriendo MemBrain: {}", e);
            return;
        }
    };

    // Step 1: Read experience
    let experience = read_experience(&mut db);

    println!(
        "[NEUROPLAST] Experiencia: {} weights, {} eventos, {} evaluaciones",
        experience.router_weights.len(),
        experience.selection_events.len(),
        experience.evaluations.len()
    );

    // Step 2: Generate new rules
    let new_rules = generate_new_rules(&experience);

    // Step 3: Apply rules
    if !new_rules.is_empty() {
        apply_rules_hot(&new_rules, RULES_FILE);
    }

    println!(
        "[NEUROPLAST] Ciclo completado - {} reglas activas",
        new_rules.len()
    );
}

/// Get current rules
pub fn get_current_rules() -> Vec<RoutingRule> {
    // MemBrain query returns empty vec - rules are managed via rules.json
    Vec::new()
}

/// Force sync rules file
pub fn sync_rules_file() {
    let rules = get_current_rules();
    if !rules.is_empty() {
        apply_rules_hot(&rules, RULES_FILE);
    }
}
